INSERT INTO vaccines (name, presentation, recommended_weeks, trimester, doses, dose_interval, priority, contraindicated, observations, educational_info) VALUES
('Hepatite B', 'Intramuscular', 'Qualquer idade gestacional', NULL, 3, '0-1-6 meses', 'Muito Alta', false, 'Pode ser administrada em qualquer trimestre. Esquema completo: 3 doses.', 'Protege contra hepatite B, que pode ser transmitida para o bebê durante o parto.'),
('dTpa (Tríplice Bacteriana)', 'Intramuscular', '20-36 semanas', 2, 1, 'Dose única a cada gestação', 'Muito Alta', false, 'Idealmente entre 27-36 semanas. Deve ser repetida a cada gestação.', 'Protege contra difteria, tétano e coqueluche. Anticorpos passam para o bebê através da placenta.'),
('Influenza (Gripe)', 'Intramuscular', 'Qualquer idade gestacional', NULL, 1, 'Anual', 'Alta', false, 'Recomendada anualmente, especialmente durante a campanha de vacinação.', 'Protege contra complicações graves da gripe durante a gravidez.'),
('COVID-19', 'Intramuscular', 'Qualquer idade gestacional', NULL, 2, 'Conforme esquema vigente', 'Muito Alta', false, 'Seguir esquema vacinal vigente do Ministério da Saúde.', 'Protege contra formas graves de COVID-19 durante a gestação.'),
('Hepatite A', 'Intramuscular', 'Qualquer idade gestacional', NULL, 2, '0-6 meses', 'Média', false, 'Indicada para gestantes em áreas de risco ou com condições especiais.', 'Protege contra hepatite A, especialmente importante em áreas endêmicas.'),
('Febre Amarela', 'Subcutânea', 'Evitar durante gestação', NULL, 1, 'Dose única', 'Baixa', true, 'Contraindicada na gestação. Avaliar risco-benefício em áreas endêmicas.', 'Vacina de vírus vivo atenuado. Só deve ser administrada se o risco de exposição for muito alto.'),
('Tríplice Viral (SCR)', 'Subcutânea', 'Contraindicada', NULL, 2, '0-1 mês', 'Baixa', true, 'Contraindicada durante a gestação. Vacinar no pós-parto imediato se necessário.', 'Protege contra sarampo, caxumba e rubéola. Deve ser evitada durante a gravidez.'),
('Varicela (Catapora)', 'Subcutânea', 'Contraindicada', NULL, 2, '0-1 mês', 'Baixa', true, 'Contraindicada na gestação. Administrar no pós-parto se não for imune.', 'Vacina de vírus vivo atenuado. Contraindicada durante a gravidez.'),
('Pneumocócica', 'Intramuscular', 'Qualquer idade gestacional', NULL, 1, 'Dose única', 'Média', false, 'Indicada para gestantes com condições de risco (asma, diabetes, etc).', 'Protege contra infecções pneumocócicas graves.'),
('Meningocócica ACWY', 'Intramuscular', 'Qualquer idade gestacional', NULL, 1, 'Dose única', 'Média', false, 'Indicada para gestantes em situações de risco epidemiológico.', 'Protege contra meningite causada pelos sorogrupos A, C, W e Y.'),
('Meningocócica B', 'Intramuscular', 'Qualquer idade gestacional', NULL, 2, '0-1 mês', 'Média', false, 'Indicada para gestantes em situações de risco epidemiológico.', 'Protege contra meningite causada pelo sorogrupo B.'),
('HPV', 'Intramuscular', 'Contraindicada', NULL, 2, '0-2 meses', 'Baixa', true, 'Não recomendada durante a gestação. Completar esquema após o parto.', 'Protege contra o papilomavírus humano. Deve ser adiada para após o parto.'),
('Raiva', 'Intramuscular', 'Apenas se exposição', NULL, 4, 'Esquema de pós-exposição', 'Alta', false, 'Indicada apenas em caso de exposição ao vírus da raiva.', 'Profilaxia pós-exposição. Deve ser administrada imediatamente após exposição de risco.');
