-- Inserir vacinas recomendadas para gestantes
-- Execute este SQL no Supabase SQL Editor

INSERT INTO vaccines (name, presentation, recommended_weeks, doses, dose_interval, priority, contraindicated, trimester, educational_info, observations, contraindication_note, reinforcement_info) VALUES
('Hepatite B', 'Intramuscular', '0-40 semanas', 3, '0, 1 e 6 meses', 'Alta', false, null, 'Protege contra a hepatite B, uma infecção viral que pode ser transmitida da mãe para o bebê durante o parto.', 'Pode ser aplicada em qualquer período da gestação. Se você já tem o esquema completo, não precisa repetir.', null, 'Reforços não são necessários após completar as 3 doses.'),
('dTpa (Tríplice Bacteriana Acelular)', 'Intramuscular', '20-36 semanas', 1, 'Dose única a cada gestação', 'Muito Alta', false, 2, 'Protege a mãe e o bebê contra difteria, tétano e coqueluche. A imunização durante a gravidez transfere anticorpos para o bebê.', 'Deve ser aplicada preferencialmente entre 20 e 36 semanas. Mesmo que já tenha tomado em gestações anteriores, precisa repetir em cada gravidez.', null, 'Repetir em todas as gestações, mesmo com intervalo curto entre elas.'),
('Influenza (Gripe)', 'Intramuscular', '0-40 semanas', 1, 'Dose única anual', 'Alta', false, null, 'Protege contra a gripe, que pode causar complicações graves durante a gestação.', 'Pode ser aplicada em qualquer trimestre. É segura tanto para a mãe quanto para o bebê.', null, 'Aplicar anualmente, mesmo durante a gestação.'),
('COVID-19', 'Intramuscular', '0-40 semanas', 2, 'Conforme orientação médica', 'Muito Alta', false, null, 'Protege contra a COVID-19, reduzindo o risco de complicações graves durante a gestação.', 'Gestantes têm maior risco de desenvolver formas graves da doença. Consulte seu médico sobre qual vacina e esquema são mais adequados.', null, 'Reforços conforme orientação médica e disponibilidade.'),
('Febre Amarela', 'Subcutânea', 'Evitar durante a gestação', 1, 'Dose única', 'Alta', true, null, 'Vacina de vírus vivo atenuado, geralmente contraindicada na gestação.', 'Só deve ser aplicada em casos excepcionais, em áreas de alto risco endêmico, após avaliação médica criteriosa.', 'Contraindicada durante a gestação por ser de vírus vivo. Só aplicar em situações de risco iminente.', null),
('Hepatite A', 'Intramuscular', '14-40 semanas', 2, '6 meses entre as doses', 'Média', false, 2, 'Protege contra a hepatite A, transmitida por água e alimentos contaminados.', 'Pode ser aplicada a partir do segundo trimestre se houver risco de exposição.', null, 'Esquema de 2 doses com intervalo de 6 meses.'),
('Pneumocócica', 'Intramuscular', '14-40 semanas', 1, 'Dose única', 'Média', false, 2, 'Protege contra infecções pneumocócicas, que podem causar pneumonia e meningite.', 'Recomendada para gestantes com condições que aumentam o risco de infecção pneumocócica.', null, null),
('Meningocócica', 'Intramuscular', '14-40 semanas', 1, 'Dose única ou 2 doses', 'Média', false, 2, 'Protege contra meningite meningocócica.', 'Pode ser indicada em surtos ou para gestantes em situação de maior risco.', null, 'Depende do tipo de vacina (conjugada ou polissacarídica).');

-- Opcional: Verificar se as vacinas foram inseridas
SELECT * FROM vaccines ORDER BY name;
